version: '3.7'

services:
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes:
      - ../:/var/www/symfony:cached
      - ./logs/nginx/:/var/log/nginx:cached
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    volumes:
      - ../:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/logs:cached
